import { create } from 'zustand'

export type Language = 'en' | 'id'

type DeepStringRecord<T> = {
  [K in keyof T]: T[K] extends boolean
    ? boolean
    : T[K] extends number
    ? number
    : T[K] extends (...args: any[]) => any
    ? T[K]
    : T[K] extends readonly string[]
    ? readonly string[]
    : T[K] extends readonly (infer U)[]
    ? readonly DeepStringRecord<U>[]
    : T[K] extends object
    ? DeepStringRecord<T[K]>
    : string
}

export type Dictionary = DeepStringRecord<typeof translations['en']>

interface LanguageState {
  language: Language
  setLanguage: (lang: Language) => void
  t: () => Dictionary
}

export const translations = {
  en: {
    brand: {
      title: 'Demerit System',
      subtitle: 'Student Discipline Management System',
      schoolPortal: 'School Portal',
    },
    login: {
      username: 'Username',
      usernamePlaceholder: 'Enter username (e.g. admin, tina, ferdi)',
      email: 'Username',
      password: 'Password',
      signIn: 'Sign In',
      signingIn: 'Signing in…',
      usernameRequired: 'Please enter your username',
      emailRequired: 'Please enter your username',
      passwordRequired: 'Please enter your password',
      invalidCredentials: 'Username or password is incorrect.',
      quickDemo: 'Quick Demo Access',
    },
    nav: {
      overview: 'Overview',
      dashboard: 'Dashboard',
      management: 'Management',
      studentsAndDemerits: 'Students & Demerits',
      students: 'Students Management',
      demeritsHistory: 'Demerits History',
      administration: 'Administration',
      usersAndTeachers: 'Users & Teachers',
      classrooms: 'Classrooms',
      categories: 'Violation Categories',
      violationRules: 'Violation Rules',
      collapseSidebar: 'Collapse sidebar',
      expandSidebar: 'Expand sidebar',
      userMenu: 'User Menu',
      roleAdmin: 'Administrator',
      rolePc1: 'Homeroom Teacher',
      roleSubject: 'Subject Teacher',
    },
    header: {
      changePassword: 'Change Password',
      logout: 'Sign Out',
      activeStatus: '2024/2025 • Active',
      homeroomClass: 'Class {class}',
      pages: {
        dashboard: { title: 'Dashboard', subtitle: 'Overview, analytics & discipline statistics' },
        students: { title: 'Students & Demerits', subtitle: 'Manage student records, initial points & discipline scores' },
        studentsAdmin: { title: 'Students Management', subtitle: 'Manage student accounts, master data & discipline scoring' },
        punishments: { title: 'Demerits History', subtitle: 'Comprehensive student violations and point deductions log' },
        users: { title: 'Users & Teachers', subtitle: 'System users, teacher classroom assignments, and roles' },
        classrooms: { title: 'Classrooms', subtitle: 'Grade levels and classroom divisions' },
        categories: { title: 'Violation Categories', subtitle: 'Discipline rule classification' },
        violationRules: { title: 'Violation Rules', subtitle: 'Point deduction standards and policy rules' },
        portal: { title: 'Portal', subtitle: 'Demerit System' },
      },
    },
    notifications: {
      title: 'Discipline Notifications',
      subtitle: 'Alerts, demerits, and record deletions',
      unreadBadge: '{count} new',
      markAllRead: 'Mark all as read',
      emptyTitle: 'No Notifications Yet',
      emptyDesc: 'You have no new alerts or activity updates.',
      callParentNotice: 'Parent Meeting Required (30 Demerits)',
      viewAllDemerits: 'View All Demerits',
      recordedBy: 'Recorded by {name}',
      deletedDemerit: 'Demerit Deleted',
      newDemerit: 'Demerit Recorded',
    },
    academicYear: {
      activeYear: 'Active Academic Year',
      changeTitle: 'Change Active Academic Year',
      changeSubtitle: 'Select or enter the active academic school year. This controls system-wide reporting and dashboard data.',
      label: 'School Year (e.g. 2024/2025)',
      placeholder: 'YYYY/YYYY',
      save: 'Save Changes',
      saving: 'Saving…',
      updateSuccess: 'Active academic year updated successfully',
      setByAdmin: 'Configured by Administrator',
    },
    dashboard: {
      welcome: 'Welcome back, {name} 👋',
      adminDesc: 'Student Discipline Oversight Portal. Monitor behavior scores, violations data, and school user management in real time.',
      pc1Desc: 'Homeroom Teacher for {class}. Monitor discipline score progression and students requiring behavioral attention or parent communication.',
      subjectDesc: 'Subject Teacher. Record and manage discipline violations and demerit points across your assigned teaching classes.',
      quickActions: {
        manageStudents: 'Manage Students',
        studentsAndPoints: 'Students & Points',
        manageTeachers: 'Manage Teachers',
      },
      kpi: {
        totalStudents: 'Total Students',
        totalStudentsHelper: 'Active students registered across all classes',
        totalUsers: 'Total Users',
        totalUsersHelper: 'Admin, Homeroom & Subject Teachers',
        todayViolations: "Today's Demerits",
        todayViolationsHelper: 'Recorded on current date',
        topViolationsMonth: 'Top Violations This Month',
        topViolationsHelper: 'Types of offenses occurred this month',
        classStudents: 'Classroom Students',
        totalClassDemerits: 'Total Class Demerits',
        totalClassDemeritsHelper: 'Accumulated demerit records in homeroom class',
        attentionRequired: 'Students Needing Attention',
        attentionRequiredHelper: 'Students below 120 points (≥30 demerits: Must Call Parents)',
        safeCondition: 'Safe Condition',
        counselingNeeded: 'Counseling & Parent Call',
        initialPointsStandard: 'Standard Initial Points',
        initialPointsHelper: 'Maximum discipline baseline score per student',
        myTotalRecorded: 'Total Demerits Recorded',
        myTotalRecordedHelper: 'Accumulated demerits submitted by you',
        recordedThisMonth: 'Recorded This Month',
        taughtClasses: 'Taught Classes',
        taughtClassesHelper: 'Scope of assigned subject teaching classes',
      },
      topViolationsTitle: 'Top Violations This Month',
      topViolationsSubtitle: 'Most frequent student violations recorded during {month}',
      noViolationsMonth: 'No violations recorded this month',
      noViolationsDesc: 'Student discipline is in excellent order.',
      occurrences: '{count} occurrences',
      attentionCardTitle: 'Attention Required: Students Below Safe Score (< 120 Points)',
      attentionCardSubtitle: 'Classroom students who have accumulated 30+ demerits and require counseling or mandatory parent contact',
      allStudentsSafeTitle: 'All Students Are in Safe Standing',
      allStudentsSafeDesc: 'All students in this class maintain a discipline score of 120 points or higher (< 30 demerits accumulated).',
      viewDetail: 'View Details',
      studentCount: '{count} Students',
      recentActivityTitle: 'Recent Demerit Activity',
      recentActivitySubtitle: 'Latest student discipline and violation records submitted to the system',
      recentRecordsCount: '{count} Latest',
      viewAllRecords: 'View All Records',
      noRecentRecordsTitle: 'No Demerit Records Yet',
      noRecentRecordsDesc: 'Recently submitted demerits will appear here.',
      tableHeaders: {
        student: 'Student',
        violation: 'Violation',
        points: 'Points',
        recordedBy: 'Recorded By',
        time: 'Date / Time',
      },
      taughtClassesTitle: 'Classrooms Assigned to You',
      taughtClassesSubtitle: 'Classroom scope where you can record and monitor student violations',
      flexiblePermissions: 'You currently have flexible permissions across all available classes in the school.',
      quickLinks: 'Quick Links',
      quickLinksList: {
        studentsList: 'Students List & Score Recap',
        violationsHistory: 'Full Demerits History Log',
        violationRules: 'Violation Rules & Point Standard',
        assignClasses: 'Manage Teacher Class Assignments',
      },
      parentContactAlert: {
        title: 'Mandatory Parent Contact Alert',
        message: 'Students with 30+ accumulated demerits require PC & Reacter teachers to contact / meet parents.',
      },
    },
    disciplinePlan: {
      mainHeader: 'PROGRESSIVE DISCIPLINE PLAN (Behavior and Consequences)',
      minorOffencesHeader: '------ Minor Offences ------',
      majorOffencesHeader: '------ Major Offences ------',
      tableMinor: {
        demeritCol: 'Demerit',
        consequencesCol: 'Consequences',
        rows: [
          {
            demerit: '15 demerits',
            consequence: 'Recorded in demerit record system + PC teacher reports to Parent by phone + counseling with PC teacher',
            isKeyMilestone: false,
          },
          {
            demerit: '25 demerits',
            consequence: 'Recorded in demerit record system + PC teacher reports to Parent by phone + counseling with PC teacher',
            isKeyMilestone: false,
          },
          {
            demerit: '30 demerits',
            consequence: 'Recorded in demerit record system + PC and Reacter teachers meet the parent + counseling with Reacter teacher + Behavior Contract Social Service for 1 day',
            isKeyMilestone: true,
          },
        ],
        accumulationNote: 'The demerit record will be accumulated for one whole school year. If student has accumulated 35 demerits from Minor Offences group, a Warning Letter will be given.',
      },
      tableMajor: {
        warningLetterCol: 'Warning Letter',
        demeritCol: 'Demerit',
        consequencesCol: 'Consequences',
        rows: [
          {
            letter: '1st Warning Letter',
            demerit: '40 demerits',
            consequence: 'Social service for 5 days',
          },
          {
            letter: '2nd Warning Letter',
            demerit: '75 demerits',
            consequence: 'Join class separately for 5 days + social service for 5 days',
          },
          {
            letter: '3rd Warning Letter',
            demerit: '100 demerits',
            consequence: 'Study at home for 5 days + social service for 10 days',
          },
        ],
      },
      policyNotes: [
        'Warning Letter Consequences: Demerit records are accumulated over the course of one whole academic year.',
        'Outstanding / Star Student Award: Students who receive any Warning Letter or accumulate excessive demerits are not eligible for student honors.',
        'Grade 1 Semester Rule: Grade 1 behavioral records are evaluated in accordance with semester-specific developmental guidelines.',
      ],
      rule30Highlight: 'Rule: Every student who accumulates 30 demerits (Score ≤ 120) MUST have parents contacted / met by PC & Reacter teachers + Behavior Contract Social Service.',
    },
    students: {
      pageTitle: 'Students & Punishments',
      allClasses: 'All Classes',
      classDivision: 'Class Division',
      searchPlaceholder: 'Search by student name or class…',
      filterTitle: 'Classroom & Grade Filter',
      allGrades: 'All Grades',
      gradePrefix: 'Grade',
      resetFilter: 'Show All (Reset)',
      showingCount: 'Showing {filtered} of {total} students',
      exportCsv: 'Export Excel',
      importCsv: 'Import Excel / CSV',
      addStudent: 'Add Student',
      editStudent: 'Edit Student',
      tableHeaders: {
        nis: 'NIS',
        name: 'Name',
        class: 'Class',
        score: 'Score',
        recentDemerit: 'Recent Demerit',
        status: 'Status',
        actions: 'Actions',
      },
      noDemerits: 'None',
      mustCallParentsBadge: 'Call Parents (≥30 Demerits)',
      active: 'Active',
      inactive: 'Inactive',
      addPunishmentTitle: 'Record Punishment',
      viewHistoryTitle: 'View Punishment History',
      form: {
        nis: 'NIS *',
        nisPlaceholder: 'Student ID number',
        name: 'Full Name *',
        namePlaceholder: 'Student full name',
        classroom: 'Classroom *',
        selectClassroom: 'Select classroom…',
        initialPoints: 'Initial Points (Poin Awal)',
        initialPointsHelper: 'Student baseline score (default: 150. Can be customized with imported spreadsheet score).',
        cancel: 'Cancel',
        save: 'Save Changes',
        saving: 'Saving…',
      },
      importModal: {
        title: 'Import Students (Bulk Create / Update)',
        description: 'Upload CSV file with columns: nis, name, classroom, initial_points (optional, default 150), is_active. Existing students will be updated automatically by NIS.',
      },
    },
    common: {
      save: 'Save',
      cancel: 'Cancel',
      delete: 'Delete',
      edit: 'Edit',
      close: 'Close',
      loading: 'Loading…',
      details: 'Details',
      warning: 'Warning',
      success: 'Success',
      error: 'Error',
      pts: 'pts',
      demerits: 'demerits',
    },
  },
  id: {
    brand: {
      title: 'Demerit System',
      subtitle: 'Sistem Manajemen Poin & Pelanggaran Siswa',
      schoolPortal: 'Portal Sekolah',
    },
    login: {
      username: 'Username / Akun',
      usernamePlaceholder: 'Masukkan username (cth: admin, tina, ferdi)',
      email: 'Username / Akun',
      password: 'Kata Sandi',
      signIn: 'Masuk',
      signingIn: 'Sedang masuk…',
      usernameRequired: 'Silakan masukkan username Anda',
      emailRequired: 'Silakan masukkan username Anda',
      passwordRequired: 'Silakan masukkan kata sandi Anda',
      invalidCredentials: 'Username atau kata sandi yang Anda masukkan salah.',
      quickDemo: 'Akses Cepat Demo',
    },
    nav: {
      overview: 'Ringkasan',
      dashboard: 'Dashboard',
      management: 'Manajemen',
      studentsAndDemerits: 'Siswa & Poin Pelanggaran',
      students: 'Kelola Siswa',
      demeritsHistory: 'Histori Pelanggaran',
      administration: 'Administrasi',
      usersAndTeachers: 'Pengguna & Guru',
      classrooms: 'Daftar Kelas',
      categories: 'Kategori Pelanggaran',
      violationRules: 'Aturan Pelanggaran',
      collapseSidebar: 'Ciutkan sidebar',
      expandSidebar: 'Perluas sidebar',
      userMenu: 'Menu Pengguna',
      roleAdmin: 'Administrator',
      rolePc1: 'Wali Kelas',
      roleSubject: 'Guru Mata Pelajaran',
    },
    header: {
      changePassword: 'Ubah Password',
      logout: 'Keluar',
      activeStatus: '2024/2025 • Aktif',
      homeroomClass: 'Kelas {class}',
      pages: {
        dashboard: { title: 'Dashboard', subtitle: 'Ringkasan, analitik & statistik kedisiplinan siswa' },
        students: { title: 'Siswa & Rekap Hukuman', subtitle: 'Kelola data siswa, poin awal & skor kedisiplinan' },
        studentsAdmin: { title: 'Manajemen Siswa', subtitle: 'Kelola data master siswa dan skor kedisiplinan sekolah' },
        punishments: { title: 'Histori Seluruh Pelanggaran', subtitle: 'Catatan komprehensif pelanggaran dan pengurangan poin siswa' },
        users: { title: 'Pengguna & Guru', subtitle: 'Pengguna sistem, penugasan kelas guru, dan peran' },
        classrooms: { title: 'Daftar Kelas', subtitle: 'Tingkatan jenjang dan pembagian rombongan belajar' },
        categories: { title: 'Kategori Pelanggaran', subtitle: 'Klasifikasi kelompok aturan tata tertib' },
        violationRules: { title: 'Aturan Pelanggaran', subtitle: 'Standar pengurangan poin dan aturan sanksi' },
        portal: { title: 'Portal', subtitle: 'Demerit System' },
      },
    },
    notifications: {
      title: 'Notifikasi Kedisiplinan',
      subtitle: 'Pemberitahuan pencatatan dan penghapusan demerit',
      unreadBadge: '{count} baru',
      markAllRead: 'Tandai semua dibaca',
      emptyTitle: 'Belum Ada Notifikasi',
      emptyDesc: 'Tidak ada pemberitahuan atau aktivitas terbaru untuk Anda.',
      callParentNotice: 'Wajib Panggil Orang Tua (30 Demerit)',
      viewAllDemerits: 'Lihat Semua Pelanggaran',
      recordedBy: 'Dicatat oleh {name}',
      deletedDemerit: 'Demerit Dihapus',
      newDemerit: 'Demerit Dicatat',
    },
    academicYear: {
      activeYear: 'Tahun Ajaran Aktif',
      changeTitle: 'Ubah Tahun Ajaran Aktif',
      changeSubtitle: 'Pilih atau masukkan tahun ajaran sekolah yang aktif. Ini mengatur periode pelaporan dan dashboard sistem.',
      label: 'Tahun Ajaran (contoh: 2024/2025)',
      placeholder: 'YYYY/YYYY',
      save: 'Simpan Perubahan',
      saving: 'Menyimpan…',
      updateSuccess: 'Tahun ajaran aktif berhasil diperbarui',
      setByAdmin: 'Diatur oleh Administrator',
    },
    dashboard: {
      welcome: 'Selamat datang kembali, {name} 👋',
      adminDesc: 'Portal Pengawasan Kedisiplinan Siswa. Pantau skor perilaku, data pelanggaran, dan manajemen pengguna sekolah secara realtime.',
      pc1Desc: 'Wali Kelas {class}. Pantau perkembangan nilai perilaku dan siswa yang memerlukan bimbingan khusus atau panggilan orang tua.',
      subjectDesc: 'Guru Mata Pelajaran. Catat dan kelola poin pelanggaran kedisiplinan siswa pada kelas-kelas yang Anda ajar.',
      quickActions: {
        manageStudents: 'Kelola Siswa',
        studentsAndPoints: 'Siswa & Poin',
        manageTeachers: 'Kelola Guru',
      },
      kpi: {
        totalStudents: 'Total Siswa',
        totalStudentsHelper: 'Siswa aktif terdaftar di seluruh kelas',
        totalUsers: 'Total Pengguna',
        totalUsersHelper: 'Admin, Wali Kelas & Guru Mapel',
        todayViolations: 'Pelanggaran Hari Ini',
        todayViolationsHelper: 'Poin tercatat pada tanggal hari ini',
        topViolationsMonth: 'Top Pelanggaran Bulan Ini',
        topViolationsHelper: 'Jenis pelanggaran yang terjadi bulan ini',
        classStudents: 'Siswa di Kelas Binaan',
        totalClassDemerits: 'Total Pelanggaran Kelas',
        totalClassDemeritsHelper: 'Total akumulasi catatan hukuman siswa kelas',
        attentionRequired: 'Siswa Perlu Perhatian',
        attentionRequiredHelper: 'Siswa di bawah 120 poin (≥30 demerit: Wajib Hubungi Ortu)',
        safeCondition: 'Kondisi Aman',
        counselingNeeded: 'Butuh Konseling & Panggilan Ortu',
        initialPointsStandard: 'Standar Poin Awal',
        initialPointsHelper: 'Skor maksimal kedisiplinan per siswa',
        myTotalRecorded: 'Total Hukuman Saya Catat',
        myTotalRecordedHelper: 'Akumulasi hukuman yang Anda rekam',
        recordedThisMonth: 'Dicatat Bulan Ini',
        taughtClasses: 'Kelas yang Diajar',
        taughtClassesHelper: 'Lingkup kelas penugasan guru mapel',
      },
      topViolationsTitle: 'Top Pelanggaran Bulan Ini',
      topViolationsSubtitle: 'Frekuensi pelanggaran terbanyak yang dicatat selama bulan {month}',
      noViolationsMonth: 'Belum ada pelanggaran bulan ini',
      noViolationsDesc: 'Kedisiplinan siswa berada dalam kondisi sangat tertib.',
      occurrences: '{count} kejadian',
      attentionCardTitle: 'Perhatian Khusus: Siswa di Bawah Skor Aman (< 120 Poin)',
      attentionCardSubtitle: 'Daftar siswa di kelas Anda yang telah mengumpulkan 30+ demerit dan memerlukan pendampingan atau pemanggilan orang tua',
      allStudentsSafeTitle: 'Semua Siswa Berada di Skor Aman',
      allStudentsSafeDesc: 'Seluruh siswa di kelas memiliki nilai kedisiplinan di atas atau sama dengan 120 poin (< 30 demerit).',
      viewDetail: 'Lihat Detail',
      studentCount: '{count} Siswa',
      recentActivityTitle: 'Aktivitas Pelanggaran Terakhir',
      recentActivitySubtitle: 'Catatan pelanggaran kedisiplinan siswa yang baru saja dimasukkan ke dalam sistem',
      recentRecordsCount: '{count} Terbaru',
      viewAllRecords: 'Lihat Semua Catatan',
      noRecentRecordsTitle: 'Belum Ada Catatan Pelanggaran',
      noRecentRecordsDesc: 'Catatan demerit yang baru direkam akan ditampilkan di sini.',
      tableHeaders: {
        student: 'Siswa',
        violation: 'Pelanggaran',
        points: 'Poin',
        recordedBy: 'Pencatat',
        time: 'Waktu',
      },
      taughtClassesTitle: 'Kelas yang Ditugaskan kepada Anda',
      taughtClassesSubtitle: 'Ruang lingkup kelas tempat Anda dapat mencatat dan memantau pelanggaran siswa',
      flexiblePermissions: 'Anda saat ini memiliki izin fleksibel untuk seluruh kelas yang tersedia di sekolah.',
      quickLinks: 'Tautan Cepat',
      quickLinksList: {
        studentsList: 'Daftar Siswa & Rekap Hukuman',
        violationsHistory: 'Histori Seluruh Pelanggaran',
        violationRules: 'Daftar Aturan Pelanggaran',
        assignClasses: 'Atur Kelas Guru Mapel',
      },
      parentContactAlert: {
        title: 'Peringatan Wajib Hubungi Orang Tua',
        message: 'Siswa dengan akumulasi 30+ demerit wajib dihubungi / ditemui orang tuanya oleh Wali Kelas & Guru Reacter.',
      },
    },
    disciplinePlan: {
      mainHeader: 'PROGRESSIVE DISCIPLINE PLAN (Behavior and Consequences)',
      minorOffencesHeader: '------ Minor Offences ------',
      majorOffencesHeader: '------ Major Offences ------',
      tableMinor: {
        demeritCol: 'Demerit',
        consequencesCol: 'Consequences (Konsekuensi)',
        rows: [
          {
            demerit: '15 demerits',
            consequence: 'Dicatat di sistem rekap demerit + Wali kelas melaporkan ke Orang Tua via telepon + konseling dengan wali kelas',
            isKeyMilestone: false,
          },
          {
            demerit: '25 demerits',
            consequence: 'Dicatat di sistem rekap demerit + Wali kelas melaporkan ke Orang Tua via telepon + konseling dengan wali kelas',
            isKeyMilestone: false,
          },
          {
            demerit: '30 demerits',
            consequence: 'Dicatat di sistem rekap demerit + Wali kelas & Guru Reacter bertemu orang tua + konseling dengan Guru Reacter + Kontrak Perilaku Bakti Sosial 1 hari',
            isKeyMilestone: true,
          },
        ],
        accumulationNote: 'Catatan demerit diakumulasikan selama satu tahun ajaran penuh. Jika siswa telah mengumpulkan 35 demerit dari kelompok Minor Offences, Surat Peringatan (Warning Letter) akan diberikan.',
      },
      tableMajor: {
        warningLetterCol: 'Warning Letter',
        demeritCol: 'Demerit',
        consequencesCol: 'Consequences (Konsekuensi)',
        rows: [
          {
            letter: '1st Warning Letter',
            demerit: '40 demerits',
            consequence: 'Bakti sosial selama 5 hari',
          },
          {
            letter: '2nd Warning Letter',
            demerit: '75 demerits',
            consequence: 'Mengikuti kelas terpisah selama 5 hari + bakti sosial 5 hari',
          },
          {
            letter: '3rd Warning Letter',
            demerit: '100 demerits',
            consequence: 'Belajar mandiri di rumah selama 5 hari + bakti sosial 10 hari',
          },
        ],
      },
      policyNotes: [
        'Konsekuensi Surat Peringatan: Catatan demerit diakumulasikan sepanjang 1 tahun ajaran akademik penuh.',
        'Kelayakan Penghargaan Bintang/Outstanding: Siswa yang menerima Surat Peringatan atau demerit berlebih tidak memenuhi syarat untuk penghargaan siswa berprestasi.',
        'Aturan Semester Kelas 1: Evaluasi perilaku Kelas 1 mengikuti ketentuan khusus berbasis semester.',
      ],
      rule30Highlight: 'Aturan: Setiap siswa yang mencapai 30 demerit (Skor ≤ 120) WAJIB dihubungi / ditemui orang tuanya oleh Wali Kelas & Guru Reacter + Kontrak Perilaku Bakti Sosial.',
    },
    students: {
      pageTitle: 'Daftar Siswa & Poin Pelanggaran',
      allClasses: 'Semua Kelas',
      classDivision: 'Pembagian Kelas',
      searchPlaceholder: 'Cari berdasarkan nama siswa atau kelas…',
      filterTitle: 'Filter Kelas & Tingkat',
      allGrades: 'Semua Tingkat',
      gradePrefix: 'Kelas',
      resetFilter: 'Tampilkan Semua (Reset)',
      showingCount: 'Menampilkan {filtered} dari {total} siswa',
      exportCsv: 'Export Excel',
      importCsv: 'Import Excel / CSV',
      addStudent: 'Tambah Siswa',
      editStudent: 'Edit Siswa',
      tableHeaders: {
        nis: 'NIS',
        name: 'Nama',
        class: 'Kelas',
        score: 'Skor',
        recentDemerit: 'Demerit Terakhir',
        status: 'Status',
        actions: 'Aksi',
      },
      noDemerits: 'Tidak ada',
      mustCallParentsBadge: 'Hubungi Ortu (≥30 Demerit)',
      active: 'Aktif',
      inactive: 'Nonaktif',
      addPunishmentTitle: 'Catat Pelanggaran',
      viewHistoryTitle: 'Lihat Riwayat Pelanggaran',
      form: {
        nis: 'NIS *',
        nisPlaceholder: 'Nomor Induk Siswa',
        name: 'Nama Lengkap *',
        namePlaceholder: 'Nama lengkap siswa',
        classroom: 'Kelas *',
        selectClassroom: 'Pilih kelas…',
        initialPoints: 'Poin Awal (Initial Points)',
        initialPointsHelper: 'Poin dasar siswa (default: 150. Dapat disesuaikan dengan nilai dari spreadsheet/excel).',
        cancel: 'Batal',
        save: 'Simpan Perubahan',
        saving: 'Menyimpan…',
      },
      importModal: {
        title: 'Import Siswa (Bulk Create / Update)',
        description: 'Upload file CSV dengan kolom: nis, name, classroom, initial_points (opsional, default 150), is_active. Siswa yang sudah ada akan otomatis diperbarui berdasarkan NIS.',
      },
    },
    common: {
      save: 'Simpan',
      cancel: 'Batal',
      delete: 'Hapus',
      edit: 'Edit',
      close: 'Tutup',
      loading: 'Memuat…',
      details: 'Detail',
      warning: 'Peringatan',
      success: 'Berhasil',
      error: 'Terjadi Kesalahan',
      pts: 'poin',
      demerits: 'demerit',
    },
  },
} as const

export const useLanguageStore = create<LanguageState>((set, get) => ({
  language: (localStorage.getItem('demerit_system_lang') as Language) || 'en',
  setLanguage: (lang: Language) => {
    localStorage.setItem('demerit_system_lang', lang)
    set({ language: lang })
  },
  t: () => {
    const lang = get().language
    return translations[lang] ?? translations.en
  },
}))

